[project]
name = "ghtrack"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "python-dateutil>=2.8.0",
    "httpx>=0.27.0",
    "trio>=0.27.0",
]
